import { render } from 'vitest-browser-svelte';
import { page } from '@vitest/browser/context';
import { expect, test, vi } from 'vitest';
import { Schema } from 'effect';
import BehaviourScorecard from './BehaviourScorecard.svelte';
import BehaviourChart from './BehaviourChart.svelte';
import BehaviourBreakdown from './BehaviourBreakdown.svelte';
import IncidentLog from './IncidentLog.svelte';
import { ModelBehaviourResponse } from '$lib/schemas';
import sample from '$lib/server/api/demo/model-behaviour.json';

// The /models page sections (spec REFUSAL-HANDLING §12.3) over a real read-API
// body (model-behaviour.json, generated by the agent's behaviour read API).
const data = Schema.decodeUnknownSync(ModelBehaviourResponse)(sample);

test('scorecard: counts, greyed low-sample cells, click selects group and metric', async () => {
	const onSelect = vi.fn();
	render(BehaviourScorecard, { rates: data.rates, rows: data.scorecard, selected: 'model_b', metric: 'nudged_per_session', onSelect });
	const cell = page.getByTestId('cell-model_a-refusals_hard_per_request');
	await expect.element(cell).toHaveTextContent('50%');
	await expect.element(cell).toHaveClass(/opacity-40/);
	await cell.click();
	expect(onSelect).toHaveBeenCalledWith('model_a', 'refusals_hard_per_request');
	await expect.element(page.getByTestId('cell-model_b-style_hits_per_1k_tokens')).toHaveTextContent('142.9 /1k');
	await expect.element(page.getByTestId('cell-model_b-nudged_per_session')).toHaveClass(/ring-sky-500/);
});

test('scorecard empty state', async () => {
	render(BehaviourScorecard, { rates: data.rates, rows: [], selected: null, metric: '', onSelect: () => {} });
	await expect.element(page.getByTestId('scorecard-empty')).toBeInTheDocument();
});

test('chart: one line per group, change markers listing their events on hover', async () => {
	const { container } = render(BehaviourChart, {
		points: data.series.points,
		rate: data.rates.find((r) => r.id === data.metric),
		since: data.since,
		until: data.until,
		bucketMs: data.series.bucketMs,
		markers: data.markers,
		selected: 'model_b'
	});
	await expect.element(page.getByTestId('behaviour-chart')).toBeInTheDocument();
	expect(container.querySelectorAll('polyline')).toHaveLength(3);
	expect(container.querySelectorAll('[data-testid="change-marker"]')).toHaveLength(1);
	const hit = container.querySelector('rect[role="presentation"]')!;
	hit.dispatchEvent(new PointerEvent('pointerenter', { bubbles: true }));
	await expect.element(page.getByTestId('marker-tooltip')).toHaveTextContent(/system prompt changed/);
	await expect.element(page.getByTestId('marker-tooltip')).toHaveTextContent(/head model model_a → model_b/);
});

test('chart empty state', async () => {
	render(BehaviourChart, { points: [], rate: data.rates[0], since: 0, until: 1, bucketMs: 3_600_000, markers: [], selected: null });
	await expect.element(page.getByTestId('chart-empty')).toBeInTheDocument();
});

test('breakdown sections per family', async () => {
	render(BehaviourBreakdown, { breakdown: data.breakdown, family: 'contract', selected: 'model_b' });
	await expect.element(page.getByText('Refusals · model_b')).toBeInTheDocument();
	await expect.element(page.getByText('Send contract · model_b')).toBeInTheDocument();
	await expect.element(page.getByText('Style · model_b')).toBeInTheDocument();
	await expect.element(page.getByText('3+ nudges')).toBeInTheDocument();
});

test('incident log: deep links, type filter, cursor pagination', async () => {
	const onType = vi.fn();
	const onLoadMore = vi.fn();
	render(IncidentLog, { rows: data.incidents.rows, hasMore: true, type: null, onType, onLoadMore });
	const link = page.getByRole('link').first();
	await expect.element(link).toHaveAttribute('href', '/?room=matrix%3Aacc_a%3Aroom%3A%21r1%3Ax&session=s1');
	await expect.element(page.getByText(/refused \(distillation\) by model_a/)).toBeInTheDocument();
	await expect.element(page.getByText('redone 1')).toBeInTheDocument();
	await page.getByRole('button', { name: 'redo' }).click();
	expect(onType).toHaveBeenCalledWith('redo');
	await page.getByRole('button', { name: 'Load more' }).click();
	expect(onLoadMore).toHaveBeenCalled();
});

test('incident log empty state', async () => {
	render(IncidentLog, { rows: [], hasMore: false, type: 'nudge', onType: () => {}, onLoadMore: () => {} });
	await expect.element(page.getByTestId('incidents-empty')).toBeInTheDocument();
});
