import { render } from 'vitest-browser-svelte';
import { page } from '@vitest/browser/context';
import { expect, test, vi } from 'vitest';
import { Schema } from 'effect';
import BehaviourScorecard from './BehaviourScorecard.svelte';
import BehaviourChart from './BehaviourChart.svelte';
import BehaviourBreakdown from './BehaviourBreakdown.svelte';
import IncidentLog from './IncidentLog.svelte';
import BehaviourOverview from './BehaviourOverview.svelte';
import BehaviourMix from './BehaviourMix.svelte';
import { ModelBehaviourResponse } from '$lib/schemas';
import sample from '$lib/server/api/demo/model-behaviour.json';

// The /models page sections (spec REFUSAL-HANDLING §12.3) over a real read-API
// body (model-behaviour.json, generated by the agent's behaviour read API).
const data = Schema.decodeUnknownSync(ModelBehaviourResponse)(sample);
const seriesOf = (metric: string) =>
	(sample as unknown as { demoSeries: Record<string, { bucketMs: number; kind: string; points: typeof data.series.points }> }).demoSeries[metric]!;

test('scorecard: counts, greyed low-sample cells, click selects group and metric', async () => {
	const onSelect = vi.fn();
	render(BehaviourScorecard, { rates: data.rates, rows: data.scorecard, selected: 'model_b', metric: 'nudged_per_session', onSelect });
	const cell = page.getByTestId('cell-model_a-refusals_hard_per_request');
	await expect.element(cell).toHaveTextContent('50%');
	await expect.element(cell).toHaveClass(/opacity-40/);
	await cell.click();
	expect(onSelect).toHaveBeenCalledWith('model_a', 'refusals_hard_per_request');
	await expect.element(page.getByTestId('cell-model_b-style_hits_per_1k_tokens')).toHaveTextContent('142.9 /1k');
	await expect.element(page.getByTestId('cell-model_b-nudged_per_session')).toHaveClass(/ring-sky-500/);
});

test('scorecard empty state', async () => {
	render(BehaviourScorecard, { rates: data.rates, rows: [], selected: null, metric: '', onSelect: () => {} });
	await expect.element(page.getByTestId('scorecard-empty')).toBeInTheDocument();
});

test('chart: one line per group, change markers listing their events on hover', async () => {
	const series = seriesOf('refusals_hard_per_request');
	const { container } = render(BehaviourChart, {
		points: series.points,
		rate: data.rates.find((r) => r.id === 'refusals_hard_per_request'),
		since: data.since,
		until: data.until,
		bucketMs: series.bucketMs,
		markers: data.markers,
		selected: 'model_b'
	});
	await expect.element(page.getByTestId('behaviour-chart')).toBeInTheDocument();
	expect(container.querySelectorAll('polyline')).toHaveLength(3);
	expect(container.querySelectorAll('[data-testid="change-marker"]')).toHaveLength(1);
	const hit = container.querySelector('rect[role="presentation"]')!;
	hit.dispatchEvent(new PointerEvent('pointerenter', { bubbles: true }));
	await expect.element(page.getByTestId('marker-tooltip')).toHaveTextContent(/system prompt changed/);
	await expect.element(page.getByTestId('marker-tooltip')).toHaveTextContent(/head model model_a → model_b/);
});

test('chart empty state', async () => {
	render(BehaviourChart, { points: [], rate: data.rates[0], since: 0, until: 1, bucketMs: 3_600_000, markers: [], selected: null });
	await expect.element(page.getByTestId('chart-empty')).toBeInTheDocument();
});

test('breakdown sections per family', async () => {
	render(BehaviourBreakdown, { breakdown: data.breakdown, family: 'contract', selected: 'model_b' });
	await expect.element(page.getByText('Refusals · model_b')).toBeInTheDocument();
	await expect.element(page.getByText('Send contract · model_b')).toBeInTheDocument();
	await expect.element(page.getByText('Style · model_b')).toBeInTheDocument();
	await expect.element(page.getByText('3+ nudges')).toBeInTheDocument();
});

test('incident log: deep links, type filter, cursor pagination', async () => {
	const onType = vi.fn();
	const onLoadMore = vi.fn();
	render(IncidentLog, { rows: data.incidents.rows, hasMore: true, type: null, onType, onLoadMore });
	const link = page.getByRole('link').first();
	await expect.element(link).toHaveAttribute('href', '/?room=matrix%3Aacc_a%3Aroom%3A%21r1%3Ax&session=s1');
	await expect.element(page.getByText(/refused 2× \(distillation, safety\), last observed/)).toBeInTheDocument();
	await expect.element(page.getByText('redone 1')).toBeInTheDocument();
	await page.getByRole('button', { name: 'redone', exact: true }).click();
	expect(onType).toHaveBeenCalledWith('redo');
	await page.getByRole('button', { name: 'Load more' }).click();
	expect(onLoadMore).toHaveBeenCalled();
});

test('incident log empty state', async () => {
	render(IncidentLog, { rows: [], hasMore: false, type: 'nudge', onType: () => {}, onLoadMore: () => {} });
	await expect.element(page.getByTestId('incidents-empty')).toBeInTheDocument();
});

test('scorecard: header clicks sort, labels follow the name switch', async () => {
	const onSort = vi.fn();
	render(BehaviourScorecard, {
		rates: data.rates,
		rows: data.scorecard,
		selected: null,
		metric: null,
		sort: 'group',
		dir: 'desc',
		labelOf: (g: string) => data.models?.[g]?.id ?? g,
		onSelect: () => {},
		onSort
	});
	const groups = page.getByTestId('scorecard-group');
	await expect.element(groups.first()).toHaveTextContent('vendor/model-b');
	await expect.element(groups.nth(2)).toHaveTextContent('vendor/cap-model');
	await page.getByTestId('sort-nudged_per_session').click();
	expect(onSort).toHaveBeenCalledWith('nudged_per_session');
	await page.getByTestId('sort-volume').click();
	expect(onSort).toHaveBeenCalledWith('volume');
});

test('overview: every rate, empty ones say so; a pick plots it', async () => {
	const onPick = vi.fn();
	render(BehaviourOverview, {
		rates: data.rates,
		metrics: data.overview!.metrics,
		since: data.since,
		until: data.until,
		bucketMs: data.overview!.bucketMs,
		onPick
	});
	await expect.element(page.getByTestId('overview-nudged_per_session')).toHaveTextContent(/2 \/ 3/);
	await expect.element(page.getByTestId('overview-gave_up_per_nudged')).toHaveTextContent(/none recorded: 0 of 2 sessions nudged/);
	await page.getByTestId('overview-refusals_judged_per_request').click();
	expect(onPick).toHaveBeenCalledWith('refusals_judged_per_request');
});

test('chart: a keyed family plots one line per key; an empty one explains itself', async () => {
	const types = seriesOf('mix:failure_type');
	const { container } = render(BehaviourChart, {
		points: types.points,
		rate: undefined,
		option: data.charts!.find((c) => c.id === 'mix:failure_type'),
		kind: 'count',
		since: data.since,
		until: data.until,
		bucketMs: types.bucketMs,
		markers: [],
		selected: 'model_b',
		scope: 'model_b'
	});
	expect(container.querySelectorAll('polyline')).toHaveLength(1);
	await expect.element(page.getByText('text_only').first()).toBeInTheDocument();
});

test('chart: empty family', async () => {
	render(BehaviourChart, {
		points: [],
		rate: undefined,
		option: data.charts!.find((c) => c.id === 'mix:no_reply_intent'),
		kind: 'count',
		since: 0,
		until: 1,
		bucketMs: 3_600_000,
		markers: [],
		selected: null
	});
	await expect.element(page.getByTestId('chart-empty')).toHaveTextContent(/No no_reply intent after a nudge recorded in this window/);
});

test('mix tables: per group counts with shares; empty families say so', async () => {
	const onChart = vi.fn();
	const empty = { id: 'after_correction', label: 'After the correction', keys: [], rows: [] };
	render(BehaviourMix, { tables: [...data.mix!.filter((t) => t.id !== 'after_correction'), empty], selected: 'model_b', onChart });
	const types = page.getByTestId('mix-failure_type');
	await expect.element(types).toHaveTextContent(/model_a\s*4\s*4\s*100%/);
	await expect.element(page.getByTestId('mix-judged_refusal_reason')).toHaveTextContent(/safety/);
	await expect.element(page.getByTestId('mix-no_reply_intent')).toHaveTextContent(/abandoned_written_reply/);
	await expect.element(page.getByTestId('mix-after_correction').getByTestId('mix-empty')).toBeInTheDocument();
	await types.getByRole('button', { name: 'over time' }).click();
	expect(onChart).toHaveBeenCalledWith('failure_type');
});

test('incident log: a filtered page that found nothing yet offers to look further back', async () => {
	const onType = vi.fn();
	const onLoadMore = vi.fn();
	render(IncidentLog, { rows: [], hasMore: true, type: 'ending', onType, onLoadMore });
	await expect.element(page.getByTestId('incidents-empty')).toHaveTextContent(/No judged ending fired incidents among the sessions looked at so far/);
	await page.getByRole('button', { name: 'Look further back' }).click();
	expect(onLoadMore).toHaveBeenCalled();
	// The active type toggles off.
	await page.getByTestId('incident-type-ending').click();
	expect(onType).toHaveBeenCalledWith(null);
});
