import { render } from 'vitest-browser-svelte';
import { page } from '@vitest/browser/context';
import { expect, test } from 'vitest';
import Rollout from './Rollout.svelte';
import type { DecisionEvaluation } from '$lib/schemas';
import rows from '$lib/server/api/demo/decision-evaluations.json';

// ── Harness rendering (spec SESSION-RECORDS §4, §8) ─────────────────────────────

// Harness injection messages (harness.kind = 'injection') render with a badge
// labelled "harness injection", not as plain model tool calls.
test('renders harness injection toolCall with harness injection badge', async () => {
	const messages = [
		{
			role: 'assistant',
			harness: { kind: 'injection', decisionGroup: 'dg-abc' },
			content: [{ type: 'toolCall', id: 'tc1', name: 'read_session_record', arguments: { session_id: 'ses_abc' } }]
		},
		{
			role: 'toolResult',
			harness: { kind: 'injection' },
			toolCallId: 'tc1',
			content: 'some record text'
		}
	];
	render(Rollout, { messages, decisionEvaluations: [] });

	await expect.element(page.getByText('harness injection', { exact: true })).toBeInTheDocument();
	// The underlying tool call name must also render.
	await expect.element(page.getByText('read_session_record', { exact: false })).toBeInTheDocument();
});

// A harness record-turn user prompt (harness.kind = 'record_turn') renders as the
// "Session record" section divider, with the prompt collapsed under a
// "harness prompt" marker (not as a plain user turn).
test('renders record_turn user prompt as a Session record section with a collapsed harness prompt', async () => {
	const messages = [
		{ role: 'user', harness: { kind: 'record_turn' }, content: 'synthesize your record now' }
	];
	render(Rollout, { messages, decisionEvaluations: [] });

	await expect.element(page.getByText('Session record', { exact: true })).toBeInTheDocument();
	await expect.element(page.getByText('harness prompt', { exact: true })).toBeInTheDocument();
	// Collapsed by default; one click shows it.
	const prompt = page.getByText('synthesize your record now', { exact: true });
	await expect.element(prompt).not.toBeVisible();
	await page.getByText('harness prompt', { exact: true }).click();
	await expect.element(prompt).toBeVisible();
});

// Inline decision cards from rows the real engine writes (decision-evaluations.json,
// generated by test/decision-evaluation-fixture.test.ts): the collapsed records card
// summarizes the whole group, and the jump-link target id exists.
test('renders inline decision cards with group summaries from real engine rows', async () => {
	const evaluations: DecisionEvaluation[] = rows.map((row, i) => ({
		...row,
		id: i + 1,
		ts: 1000 + i,
		latencyMs: 100
	}));
	const messages = [
		{
			role: 'assistant',
			harness: { kind: 'injection', decisionGroup: 'dg-records-demo' },
			content: [{ type: 'toolCall', id: 'tc2', name: 'read_session_record', arguments: { session_id: 'ses_v8n2ke' } }]
		},
		{
			role: 'toolResult',
			toolCallId: 'tc2',
			content: 'record text',
			harness: { kind: 'injection', decisionGroup: 'dg-records-demo' }
		},
		{ role: 'assistant', content: [{ type: 'text', text: 'On it.' }] }
	];
	const { container } = render(Rollout, { messages, decisionEvaluations: evaluations });

	await expect.element(page.getByText('records', { exact: true })).toBeInTheDocument();
	await expect.element(page.getByText('injected ses_v8n2ke', { exact: true })).toBeInTheDocument();
	await expect.element(page.getByText('1 of 3 fell back', { exact: true })).toBeInTheDocument();
	await expect.element(page.getByText('image · image-chat · +image-generation', { exact: true })).toBeInTheDocument();
	expect(container.querySelector('#decision-dg-records-demo')).not.toBeNull();
	expect(container.querySelector('#decision-dg-routing-demo')).not.toBeNull();

	// Expanded: per-candidate answers with the noul probability.
	await page.getByText('injected ses_v8n2ke', { exact: true }).click();
	await expect.element(page.getByText('p=0.83', { exact: true })).toBeInTheDocument();
});

// ── Resume turn test (pre-existing) ──────────────────────────────────────────

// A resumed session (reply-to-agent-msg) appends a fresh `triggerGroup` final user
// turn AFTER the completed transcript, so it lands inside the rollout slice —
// `rolloutStartIndex` (src/observability/server/handlers.ts) skips only the leading
// head run, so only a fresh session's kickoff is a head turn. The resume turn must
// render as a trigger turn via the verbatim MessageBlock, not fall through to the
// raw-JSON fallback (the "resume turn shows as JSON in the console" bug).
test('renders an in-rollout resume triggerGroup as a trigger turn, not raw JSON', async () => {
	const messages = [
		{ role: 'assistant', content: [{ type: 'text', text: 'earlier reply' }] },
		{
			type: 'triggerGroup',
			content: '<system>runtime</system>\n\nnew user message',
			tier: 'trigger',
			tokenEstimate: 42,
			timestamp: 123
		}
	];
	render(Rollout, { messages });

	// The verbatim MessageBlock gutter renders the tier label and the message type as
	// their own elements; the raw-JSON fallback would instead bury them inside a single
	// JSON <pre> blob, so an exact-text match on each is a decisive proof of the fix.
	await expect.element(page.getByText('trigger', { exact: true })).toBeInTheDocument();
	await expect.element(page.getByText('triggerGroup', { exact: true })).toBeInTheDocument();
});
