import { describe, expect, it } from 'vitest';
import { Schema } from 'effect';
import {
	attemptBeforeNudge,
	auditFindings,
	checkKind,
	consequenceLabel,
	evaluationsForCall,
	eventsForEvaluation,
	gateEvaluations,
	nudgeOf,
	overrideCodes,
	splitQuestionId,
	wordDiff
} from './checks';
import { rowVerdictLabel } from './decisions';
import { SessionDecisionsResponse, SessionDetailResponse, type DecisionEvaluation } from './schemas';
import fixture from '$lib/server/api/demo/refusal-session.json';

// Gate records as the agent's evaluator writes them (refusal-session.json is
// generated by the real gate: test/refusal-session-fixture.test.ts).
const detail = Schema.decodeUnknownSync(SessionDetailResponse)(fixture.detail);
const rows = [...Schema.decodeUnknownSync(SessionDecisionsResponse)(fixture.decisions).evaluations];

function row(over: Partial<DecisionEvaluation>): DecisionEvaluation {
	return {
		id: 1, ts: 10, decisionGroup: 'g', point: 'checks', agent: null, timelineKey: null, agentSessionId: 's',
		triggerEventId: null, candidateSessionId: null, source: 'model', reason: null, verdictJson: null,
		answersJson: null, stateJson: null, questionsJson: null, servedModel: null, servedVersion: null,
		latencyMs: null, inputTokens: null, costUsd: null, checkpoint: 'send', branchNo: 0, toolCallId: 'c',
		attemptNo: null, consequence: 'sent', ...over
	};
}

describe('gateEvaluations', () => {
	const evals = gateEvaluations(rows, detail.checks);

	it('groups one evaluation per decision group with its anchor', () => {
		expect(evals.map((e) => [e.toolCallId, e.consequence])).toEqual([
			['call-refused', 'redo'],
			['call-sent', 'observed']
		]);
	});

	it('a judged refusal: the fired question, its probability and threshold, the member and latency', () => {
		const refused = evals[0]!;
		expect(refused.fired.map((c) => c.code)).toEqual(['refusal_safety']);
		const safety = refused.fired[0]!;
		expect(safety).toMatchObject({ kind: 'refusal', method: 'judged', probability: 0.93, threshold: 0.8, source: 'message' });
		expect(safety.description).toContain('safety');
		expect(refused.latencyMs).toBe(640);
		expect(refused.members).toEqual(['decider · vendor/decider-1-20261001']);
		expect(refused.clean).toBe(false);
		expect(refused.questionCount).toBe(7);
	});

	it('a pattern hit decides its check; judged checks that stayed below threshold are listed, not fired', () => {
		const sent = evals[1]!;
		expect(sent.fired).toHaveLength(1);
		expect(sent.fired[0]).toMatchObject({ code: 'style_vocabulary', kind: 'style', method: 'pattern', matched: 'delve', probability: 1 });
		expect(sent.checks.filter((c) => !c.fired).every((c) => c.kind === 'refusal')).toBe(true);
	});

	it('a clean, sent evaluation collapses; an unjudged one does not', () => {
		const clean = gateEvaluations([row({ verdictJson: JSON.stringify({ fired: [], results: [{ id: 'x__message', p: 0.1, t: 0.8 }] }) })]);
		expect(clean[0]!.clean).toBe(true);
		const unjudged = gateEvaluations([row({ source: 'heuristic', reason: 'timeout', verdictJson: JSON.stringify({ unjudged: true }), consequence: 'sent_unjudged' })]);
		expect(unjudged[0]!.clean).toBe(false);
		expect(unjudged[0]!.unjudged).toBe(true);
		expect(unjudged[0]!.unjudgedReasons).toEqual(['timeout']);
	});

	it('ignores other points and malformed verdicts', () => {
		expect(gateEvaluations([row({ point: 'routing' })])).toEqual([]);
		expect(() => gateEvaluations([row({ verdictJson: '{not json' })])).not.toThrow();
	});

	it('links the refusal events written for an evaluation', () => {
		expect(eventsForEvaluation(detail.refusalEvents ?? [], evals[0]!).map((e) => e.outcome)).toEqual(['redo']);
		expect(eventsForEvaluation(detail.refusalEvents ?? [], evals[1]!)).toEqual([]);
	});

	it('prefers rows re-anchored to the displayed branch', () => {
		const both = gateEvaluations([
			row({ id: 1, decisionGroup: 'a', branchNo: 0 }),
			row({ id: 2, decisionGroup: 'b', branchNo: 1 })
		]);
		expect(evaluationsForCall(both, 'c', 1).map((e) => e.decisionGroup)).toEqual(['b']);
		expect(evaluationsForCall(both, 'c', 3).map((e) => e.decisionGroup)).toEqual(['a', 'b']);
	});

	it('the decision-card label of a checks row', () => {
		expect(rowVerdictLabel(rows[0]!)).toBe('fired refusal_safety');
		expect(rowVerdictLabel(row({ verdictJson: JSON.stringify({ fired: [], results: [] }) }))).toBe('clean');
	});
});

describe('small readers', () => {
	it('question ids and kinds', () => {
		expect(splitQuestionId('refusal_safety__message')).toEqual({ code: 'refusal_safety', source: 'message' });
		expect(splitQuestionId('op_x__analysis_2')).toEqual({ code: 'op_x', source: 'analysis' });
		expect(checkKind('no_reply_intent')).toBe('contract');
		expect(checkKind('custom')).toBe('check');
	});

	it('consequences and override codes', () => {
		expect(consequenceLabel('sent_unjudged')).toBe('sent unjudged (deadline)');
		expect(overrideCodes({ message: 'x', override_checks: ['style_em_dash'] })).toEqual(['style_em_dash']);
		expect(overrideCodes({ message: 'x' })).toEqual([]);
	});

	it('nudges by marker and by the runner prompt wording', () => {
		expect(nudgeOf({ role: 'user', harness: { kind: 'forced_completion', attempt: 2, variant: 'sent_not_final' } })).toEqual({ attempt: 2, variant: 'sent_not_final' });
		expect(nudgeOf({ role: 'user', content: 'Your turn ended without sending a message. You must…' })).toEqual({ attempt: null, variant: 'not_sent' });
		expect(nudgeOf({ role: 'user', harness: { kind: 'record_turn' }, content: 'Your turn ended without sending' })).toBeNull();
		expect(nudgeOf({ type: 'interjection', content: 'hi' })).toBeNull();
	});

	it('the attempt a nudge closed', () => {
		const attempts = detail.contract!.attempts;
		expect(attemptBeforeNudge(attempts, 0, 1, 4100)?.failureTypes).toEqual(['text_only']);
		expect(attemptBeforeNudge(attempts, 1, 1, 4100)).toBeUndefined();
	});

	it('audit findings (offline audit rows, read tolerantly)', () => {
		const found = auditFindings([
			row({ point: 'audit', attemptNo: 0, verdictJson: JSON.stringify({ after_correction: 'minor_rewording', self_talk: true, types: ['text_only'] }) }),
			row({ point: 'checks' })
		]);
		expect(found).toEqual([{ attemptNo: 0, afterCorrection: 'minor_rewording', chips: ['self_talk', 'text_only'] }]);
	});

	it('word diff', () => {
		expect(wordDiff('the cat sat', 'the dog sat')).toEqual([
			{ kind: 'same', text: 'the ' },
			{ kind: 'removed', text: 'cat ' },
			{ kind: 'added', text: 'dog ' },
			{ kind: 'same', text: 'sat' }
		]);
		expect(wordDiff('', 'new')).toEqual([{ kind: 'added', text: 'new' }]);
	});
});
