import fs from "node:fs/promises";
import path from "node:path";
import { randomBytes } from "node:crypto";
import type { AgentTool } from "@earendil-works/pi-agent-core";
import { Type } from "@earendil-works/pi-ai";
import { resolveWorkspacePath } from "./workspace.js";
import { assertPublicHttpUrl } from "./ssrf.js";
import {
  buildProxyDispatcher,
  type ConcurrencyLimitedFetchClient,
} from "../enrichment/fetch-client.js";
import type { Dispatcher } from "undici";
import {
  conditionImageBufferForInference,
  type ImageProcessingOptions,
} from "../media/index.js";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Reference images (edit mode) per call. Pro accepts ~11, Flash ~14; we cap
 *  conservatively — more than a handful rarely improves an edit and bloats the
 *  request. */
const MAX_INPUT_IMAGES = 6;
const DEFAULT_OUTPUT_SUBDIR = "generated-images";
/** Pro "thinking" runs ~18s for a single image; 4K is slower. 120s is roomy. */
const DEFAULT_TIMEOUT_MS = 120_000;
/**
 * 🔑 Gemini emits the generated image AS output tokens (a 1K image ≈ 1290 tok;
 * Pro adds ~50 "thinking" tok). Some gateways default this cap very low
 * (~15 tokens), which silently truncates BEFORE any image is produced — HTTP 200,
 * `finishReason:"MAX_TOKENS"`, no image part. Setting this high is mandatory.
 */
const DEFAULT_MAX_OUTPUT_TOKENS = 32_768;
/** Hard cap on the JSON response body (a 4K base64 image is several MB). */
const RESPONSE_MAX_BYTES = 64 * 1024 * 1024;
/**
 * Per-reference byte budget for edit inputs. Reference images are billed as
 * input tokens and inflate the request, so we bound them — but generously,
 * since these are the source material for an edit and re-encoding degrades
 * quality. A reference under this budget is sent as its ORIGINAL bytes
 * (no conversion); only an over-budget reference is run through
 * `conditionImageBufferForInference` (resize + JPEG) to bring it down. 6 MiB
 * comfortably holds a high-quality multi-megapixel JPEG/PNG/WebP while still
 * capping worst-case token/memory cost across up to MAX_INPUT_IMAGES refs.
 */
const REFERENCE_IMAGE_MAX_BYTES = 6 * 1024 * 1024;
const USER_AGENT = "MikuAgent/0.1 (mikuswarm image_generate)";

const ASPECT_RATIOS = [
  "1:1",
  "2:3",
  "3:2",
  "3:4",
  "4:3",
  "4:5",
  "5:4",
  "9:16",
  "16:9",
  "21:9",
] as const;
const IMAGE_SIZES = ["512", "1K", "2K", "4K"] as const;
const MODEL_ALIASES = ["pro", "flash"] as const;

type AspectRatio = (typeof ASPECT_RATIOS)[number];
type ImageSize = (typeof IMAGE_SIZES)[number];
type ModelAlias = (typeof MODEL_ALIASES)[number];

/** A reference image as the Gemini API wants it: base64 + declared MIME. */
type ReferenceImage = { mimeType: string; data: string };

type ImageGenParams = {
  prompt?: string;
  images?: string[];
  model?: ModelAlias;
  aspect_ratio?: AspectRatio;
  image_size?: ImageSize;
  filename?: string;
};

// Minimal shape of the Gemini `:generateContent` response we read from.
type GeminiInlineData = { mimeType?: string; mime_type?: string; data?: string };
type GeminiPart = { text?: string; inlineData?: GeminiInlineData; inline_data?: GeminiInlineData };
type GeminiResponse = {
  candidates?: Array<{
    finishReason?: string;
    content?: { parts?: GeminiPart[] };
  }>;
};

export interface ImageGenToolContext {
  workspaceRoot: string;
  /** Used to download `images` reference inputs given as http(s) URLs. */
  fetchClient: ConcurrencyLimitedFetchClient;
  /** Hard fetch ceiling for reference-image downloads. */
  downloadSizeLimit: number;
  /**
   * Per-image base64 byte cap for the inline preview returned to the model.
   * The generated bytes are conditioned (resize + re-encode) to fit under this
   * before being emitted as an inline image block — same pattern as the
   * danbooru `preview` action and `read_image`.
   */
  inlineImageMaxBytes: number;
  /** Sharp resize/encode options shared with captioning + the inline paths. */
  inferenceImageOptions: ImageProcessingOptions;
  /** Optional http(s) proxy applied to the generation POST. */
  httpProxyUrl?: string;
  config?: {
    base_url?: string;
    api_key?: string;
    models?: { pro?: string; flash?: string };
    timeout_ms?: number;
    max_output_tokens?: number;
    output_subdir?: string;
  };
}

// ---------------------------------------------------------------------------
// Parameter schema
// ---------------------------------------------------------------------------

const ImageGenSchema = Type.Object(
  {
    prompt: Type.String({
      minLength: 1,
      description:
        "What to draw. For generation, describe the scene narratively (subject, setting, lighting, style). " +
        "When 'images' are provided this is the EDIT instruction (what to change / preserve).",
    }),
    images: Type.Optional(
      Type.Array(Type.String({ minLength: 1 }), {
        maxItems: MAX_INPUT_IMAGES,
        description:
          "Reference images to EDIT or compose from (1–6). Each is a workspace-relative path or an http(s) URL. " +
          "Providing any reference image switches the tool to edit mode.",
      }),
    ),
    model: Type.Optional(
      Type.Unsafe<ModelAlias>({
        type: "string",
        enum: [...MODEL_ALIASES],
        description:
          "Which model to use. 'pro' (nano banana pro — best quality, text rendering; default) or 'flash' (faster/cheaper).",
      }),
    ),
    aspect_ratio: Type.Optional(
      Type.Unsafe<AspectRatio>({
        type: "string",
        enum: [...ASPECT_RATIOS],
        description: "Output aspect ratio. Omit for the model default (1:1).",
      }),
    ),
    image_size: Type.Optional(
      Type.Unsafe<ImageSize>({
        type: "string",
        enum: [...IMAGE_SIZES],
        description:
          "Output resolution hint (longer edge). '1K'/'2K'/'4K'; '512' is flash-only. Loosely honored — treat as a quality hint.",
      }),
    ),
    filename: Type.Optional(
      Type.String({
        description:
          "Optional output basename hint (no extension needed). A collision-safe name is used if omitted.",
      }),
    ),
  },
  { additionalProperties: false },
);

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

export function createImageGenTool(context: ImageGenToolContext): AgentTool {
  const baseUrl = normalizeBaseUrl(context.config?.base_url);
  const apiKey = (context.config?.api_key ?? "").trim();
  const proModel = (context.config?.models?.pro ?? "").trim();
  const flashModel = (context.config?.models?.flash ?? "").trim();
  if (!apiKey) {
    throw new Error("image_gen.api_key must be configured.");
  }
  if (!proModel || !flashModel) {
    throw new Error("image_gen.models.pro and image_gen.models.flash must both be configured.");
  }
  // modelId is interpolated into the request URL path; reject anything that
  // could alter the path (slashes, dot-segments, etc.). Fail fast at construction.
  const MODEL_ID_PATTERN = /^[A-Za-z0-9._-]+$/;
  if (!MODEL_ID_PATTERN.test(proModel)) {
    throw new Error(`image_gen.models.pro must match ${MODEL_ID_PATTERN}, got "${proModel}".`);
  }
  if (!MODEL_ID_PATTERN.test(flashModel)) {
    throw new Error(`image_gen.models.flash must match ${MODEL_ID_PATTERN}, got "${flashModel}".`);
  }
  const models: Record<ModelAlias, string> = { pro: proModel, flash: flashModel };
  const timeoutMs = context.config?.timeout_ms ?? DEFAULT_TIMEOUT_MS;
  const maxOutputTokens = context.config?.max_output_tokens ?? DEFAULT_MAX_OUTPUT_TOKENS;
  const outputSubdir = normalizeSubdir(context.config?.output_subdir);
  const dispatcher = buildProxyDispatcher(context.httpProxyUrl);

  return {
    name: "image_generate",
    label: "Generate image",
    description:
      "Generate or edit an image with Google's Gemini \"nano banana\" models. " +
      "Provide a 'prompt' to generate from text. To EDIT, also pass 'images' (1–6 workspace paths or URLs) — " +
      "the prompt becomes the edit instruction. Defaults to the high-quality 'pro' model; pass model:'flash' for " +
      "faster/cheaper results. Optional 'aspect_ratio' and 'image_size'. The image is saved into the workspace and " +
      "returned to you as an inline preview; to post it to the chat you MUST call send_message with 'media' set to " +
      "the returned path.",
    parameters: ImageGenSchema,
    execute: async (_toolCallId, rawParams) => {
      const params = rawParams as ImageGenParams;
      const prompt = params.prompt?.trim();
      if (!prompt) {
        return textError("image_generate requires a non-empty 'prompt'.");
      }
      const alias: ModelAlias = params.model ?? "pro";
      const modelId = models[alias];
      if (params.image_size === "512" && alias !== "flash") {
        return textError(
          "image_size '512' is only supported by the flash model. Use model:'flash', or choose 1K/2K/4K.",
        );
      }

      // Edit mode: load reference images as inlineData parts.
      let refs: ReferenceImage[] = [];
      if (params.images && params.images.length > 0) {
        try {
          refs = await loadReferenceImages(params.images, context, dispatcher);
        } catch (error) {
          return textError(`Failed to load reference image: ${errMessage(error)}`);
        }
      }

      const body = buildRequestBody({ prompt, refs, aspectRatio: params.aspect_ratio, imageSize: params.image_size, maxOutputTokens });
      const url = `${baseUrl}/v1beta/models/${modelId}:generateContent`;

      let result: GeminiResponse | { httpError: ToolTextResult };
      try {
        result = await postGenerate({ url, apiKey, body, dispatcher, timeoutMs });
      } catch (error) {
        return textError(`Image generation request failed (model ${modelId}): ${errMessage(error)}`);
      }
      if ("httpError" in result) {
        return result.httpError;
      }

      const extracted = extractImage(result);
      if (!extracted.image) {
        const reason = extracted.finishReason ?? "unknown";
        const hint =
          reason === "MAX_TOKENS"
            ? "Output was truncated before any image was produced (max_output_tokens too low or prompt too long)."
            : "The model produced no image — try rephrasing the prompt.";
        const said = extracted.text ? ` Model said: ${extracted.text.slice(0, 200)}` : "";
        return textError(`No image returned (finishReason=${reason}). ${hint}${said}`);
      }

      const rawBuffer = Buffer.from(extracted.image.data, "base64");
      const ext = mimeToExtension(extracted.image.mimeType);
      let relPath: string;
      try {
        const outDir = resolveWorkspacePath(context.workspaceRoot, outputSubdir);
        await fs.mkdir(outDir, { recursive: true });
        const savedPath = await writeOutputImage(outDir, params.filename, ext, rawBuffer);
        relPath = toWorkspaceRelative(context.workspaceRoot, savedPath);
      } catch (error) {
        return textError(`Generated the image but failed to save it: ${errMessage(error)}`);
      }

      // Inline preview so the model sees what it made. Conditioning failure is
      // non-fatal — the file is already saved and deliverable by path.
      let inline: { buffer: Buffer; mimeType: string } | undefined;
      let inlineError: string | undefined;
      try {
        const rawByteBudget = Math.floor((context.inlineImageMaxBytes * 3) / 4);
        const conditioned = await conditionImageBufferForInference(rawBuffer, {
          ...context.inferenceImageOptions,
          maxBytes: rawByteBudget,
        });
        inline = { buffer: conditioned.buffer, mimeType: conditioned.mimeType };
      } catch (error) {
        // Non-fatal: the file is already saved and deliverable by path. Tools
        // in this codebase receive no logger (cf. danbooru), so surface the
        // diagnostic in the returned text rather than swallowing it silently —
        // this is how a genuine inlineImageMaxBytes misconfiguration becomes
        // visible instead of looking like the model just declined a preview.
        inline = undefined;
        inlineError = errMessage(error);
      }

      const isEdit = refs.length > 0;
      const text = [
        `## Image ${isEdit ? "edit" : "generation"}`,
        "",
        `Saved to \`${relPath}\` using \`${modelId}\` (${alias}).`,
        ...(params.aspect_ratio ? [`- aspect ratio: ${params.aspect_ratio}`] : []),
        ...(params.image_size ? [`- size hint: ${params.image_size}`] : []),
        ...(isEdit ? [`- edited from ${refs.length} reference image(s)`] : []),
        ...(inlineError ? [`- (inline preview unavailable: ${inlineError})`] : []),
        ...(extracted.text ? ["", `Model note: ${extracted.text.slice(0, 500)}`] : []),
        "",
        `To post this image to the chat, call \`send_message\` with \`media: "${relPath}"\`.`,
        "All Gemini images carry an invisible SynthID watermark.",
      ].join("\n");

      return {
        content: [
          { type: "text" as const, text },
          ...(inline
            ? [{ type: "image" as const, data: inline.buffer.toString("base64"), mimeType: inline.mimeType }]
            : []),
        ],
        details: {
          path: relPath,
          model: modelId,
          modelAlias: alias,
          isEdit,
          mimeType: extracted.image.mimeType,
          aspectRatio: params.aspect_ratio ?? null,
          imageSize: params.image_size ?? null,
          referenceImages: refs.length,
          caption: extracted.text ?? null,
        },
      };
    },
  };
}

// ---------------------------------------------------------------------------
// Request building & HTTP
// ---------------------------------------------------------------------------

export function buildRequestBody(input: {
  prompt: string;
  refs: ReferenceImage[];
  aspectRatio?: AspectRatio;
  imageSize?: ImageSize;
  maxOutputTokens: number;
}): Record<string, unknown> {
  // Reference images first, then the text instruction (matches the API's
  // edit examples). Generation is the same shape with no inlineData parts.
  const parts: Array<Record<string, unknown>> = input.refs.map((ref) => ({
    inlineData: { mimeType: ref.mimeType, data: ref.data },
  }));
  parts.push({ text: input.prompt });

  const imageConfig: Record<string, string> = {};
  if (input.aspectRatio) imageConfig.aspectRatio = input.aspectRatio;
  if (input.imageSize) imageConfig.imageSize = input.imageSize;

  return {
    contents: [{ role: "user", parts }],
    generationConfig: {
      responseModalities: ["TEXT", "IMAGE"],
      // 🔑 Mandatory — see DEFAULT_MAX_OUTPUT_TOKENS note above.
      maxOutputTokens: input.maxOutputTokens,
      ...(Object.keys(imageConfig).length > 0 ? { imageConfig } : {}),
    },
  };
}

type ToolTextResult = ReturnType<typeof textError>;

async function postGenerate(input: {
  url: string;
  apiKey: string;
  body: Record<string, unknown>;
  dispatcher: Dispatcher | undefined;
  timeoutMs: number;
}): Promise<GeminiResponse | { httpError: ToolTextResult }> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), input.timeoutMs);
  let response: Response;
  try {
    response = await globalThis.fetch(input.url, {
      method: "POST",
      signal: controller.signal,
      headers: {
        "content-type": "application/json",
        accept: "application/json",
        "user-agent": USER_AGENT,
        // The Gemini endpoint authenticates with the API key as a bearer token.
        // (When an operator gateway fronts Google, it injects real Google creds
        // downstream; Google's native x-goog-api-key header is not used here.)
        authorization: `Bearer ${input.apiKey}`,
      },
      body: JSON.stringify(input.body),
      // undici accepts `dispatcher` at runtime; routes through the proxy when set.
      ...(input.dispatcher ? { dispatcher: input.dispatcher } : {}),
    } as RequestInit);
  } catch (error) {
    clearTimeout(timeout);
    if ((error as { name?: string })?.name === "AbortError") {
      throw new Error(`timed out after ${input.timeoutMs}ms`);
    }
    throw error;
  }
  try {
    if (!response.ok) {
      const snippet = await safeReadText(response);
      // Tagged error object so the caller can return it as a tool result.
      return {
        httpError: textError(
          `Image generation failed: HTTP ${response.status}${snippet ? ` (${snippet})` : ""}.`,
        ),
      };
    }
    try {
      return (await readJsonCapped(response, controller)) as GeminiResponse;
    } catch (error) {
      // A timeout that fires mid-stream aborts `reader.read()` with an
      // AbortError; surface the same friendly message as the fetch-level abort.
      // The cap-exceeded guard throws a plain Error (not AbortError) with its
      // own explicit message, so it is not clobbered here.
      if ((error as { name?: string })?.name === "AbortError") {
        throw new Error(`timed out after ${input.timeoutMs}ms`);
      }
      throw error;
    }
  } finally {
    clearTimeout(timeout);
  }
}

/** Stream the JSON body with a running byte cap so a runaway response (or a
 *  proxy that lies about content-length) can't exhaust memory. */
async function readJsonCapped(response: Response, controller: AbortController): Promise<unknown> {
  const declared = Number(response.headers.get("content-length") ?? "");
  if (Number.isFinite(declared) && declared > RESPONSE_MAX_BYTES) {
    throw new Error(`response too large: declared content-length ${declared} > ${RESPONSE_MAX_BYTES} bytes`);
  }
  const reader = response.body?.getReader();
  if (!reader) {
    return response.json();
  }
  const chunks: Uint8Array[] = [];
  let total = 0;
  for (;;) {
    const { value, done } = await reader.read();
    if (done) break;
    if (!value) continue;
    total += value.byteLength;
    if (total > RESPONSE_MAX_BYTES) {
      controller.abort();
      throw new Error(`response exceeded ${RESPONSE_MAX_BYTES} bytes`);
    }
    chunks.push(value);
  }
  const combined = Buffer.concat(chunks.map((chunk) => Buffer.from(chunk)));
  return JSON.parse(combined.toString("utf8"));
}

async function safeReadText(response: Response): Promise<string> {
  try {
    const text = (await response.text()).trim();
    return text ? text.slice(0, 300) : "";
  } catch {
    return "";
  }
}

// ---------------------------------------------------------------------------
// Reference image loading (edit mode)
// ---------------------------------------------------------------------------

async function loadReferenceImages(
  refs: string[],
  context: ImageGenToolContext,
  dispatcher: Dispatcher | undefined,
): Promise<ReferenceImage[]> {
  void dispatcher; // URL downloads route through fetchClient, which holds its own proxy.
  const out: ReferenceImage[] = [];
  for (const raw of refs) {
    const ref = raw.trim();
    if (!ref) continue;
    if (/^https?:\/\//i.test(ref)) {
      // Defense in depth: validate the initial URL up front, and have the fetch
      // client re-validate every redirect hop (ssrfGuard) so a public URL can't
      // 302 to a private/metadata host.
      await assertPublicHttpUrl(ref);
      const fetched = await context.fetchClient.fetch(ref, {
        maxBytes: context.downloadSizeLimit,
        ssrfGuard: true,
      });
      let buffer: Buffer;
      try {
        if (fetched.statusCode < 200 || fetched.statusCode >= 300) {
          throw new Error(`HTTP ${fetched.statusCode} fetching ${ref}`);
        }
        buffer = await fs.readFile(fetched.path);
      } finally {
        await fs.unlink(fetched.path).catch(() => {});
      }
      const mime =
        imageMimeFromContentType(fetched.contentType) ?? imageMimeFromExtension(ref) ?? "image/png";
      out.push(await boundReferenceImage(buffer, mime, context));
    } else {
      const abs = resolveWorkspacePath(context.workspaceRoot, ref);
      const buffer = await fs.readFile(abs);
      const mime = imageMimeFromExtension(ref) ?? "image/png";
      out.push(await boundReferenceImage(buffer, mime, context));
    }
  }
  if (out.length === 0) {
    throw new Error("no usable reference images were provided");
  }
  return out;
}

/**
 * Bound a single reference image to {@link REFERENCE_IMAGE_MAX_BYTES}. When the
 * raw bytes are already under budget they are sent untouched (original MIME) to
 * preserve editing quality. Only an over-budget reference is conditioned
 * (resize + JPEG re-encode) via `conditionImageBufferForInference`, which caps
 * tokens and memory at the cost of one lossy pass on an image that was too big
 * to send as-is anyway.
 */
async function boundReferenceImage(
  buffer: Buffer,
  mimeType: string,
  context: ImageGenToolContext,
): Promise<ReferenceImage> {
  if (buffer.byteLength <= REFERENCE_IMAGE_MAX_BYTES) {
    return { mimeType, data: buffer.toString("base64") };
  }
  const conditioned = await conditionImageBufferForInference(buffer, {
    ...context.inferenceImageOptions,
    maxBytes: REFERENCE_IMAGE_MAX_BYTES,
  });
  return { mimeType: conditioned.mimeType, data: conditioned.buffer.toString("base64") };
}

// ---------------------------------------------------------------------------
// Response parsing
// ---------------------------------------------------------------------------

export function extractImage(payload: GeminiResponse): {
  image?: { mimeType: string; data: string };
  text?: string;
  finishReason?: string;
} {
  const candidate = payload?.candidates?.[0];
  const finishReason = candidate?.finishReason;
  const parts = candidate?.content?.parts ?? [];
  let image: { mimeType: string; data: string } | undefined;
  let text: string | undefined;
  for (const part of parts) {
    const inline = part.inlineData ?? part.inline_data;
    if (inline?.data && !image) {
      image = {
        mimeType: inline.mimeType ?? inline.mime_type ?? "image/png",
        data: inline.data,
      };
    } else if (typeof part.text === "string" && part.text.trim() && !text) {
      text = part.text.trim();
    }
  }
  return { image, text, finishReason };
}

// ---------------------------------------------------------------------------
// Output file writing
// ---------------------------------------------------------------------------

const OUTPUT_COLLISION_RETRY_CAP = 100;

async function writeOutputImage(
  dir: string,
  fileNameHint: string | undefined,
  ext: string,
  buffer: Buffer,
): Promise<string> {
  const base = sanitizeFileBaseName(fileNameHint) ?? `image-${randomBytes(6).toString("hex")}`;
  // Exclusive create (`wx`) so concurrent calls into the same dir can't pick
  // the same suffix between an existence check and the write.
  let suffix = 0;
  for (let attempt = 0; attempt <= OUTPUT_COLLISION_RETRY_CAP; attempt++) {
    const candidate =
      suffix === 0 ? path.join(dir, `${base}.${ext}`) : path.join(dir, `${base}-${suffix}.${ext}`);
    try {
      const handle = await fs.open(candidate, "wx");
      try {
        await handle.writeFile(buffer);
      } finally {
        await handle.close();
      }
      return candidate;
    } catch (error) {
      if ((error as NodeJS.ErrnoException)?.code !== "EEXIST") throw error;
      suffix += 1;
    }
  }
  const fallback = path.join(dir, `${base}-${randomBytes(6).toString("hex")}.${ext}`);
  const handle = await fs.open(fallback, "wx");
  try {
    await handle.writeFile(buffer);
  } finally {
    await handle.close();
  }
  return fallback;
}

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

function normalizeBaseUrl(value: string | undefined): string {
  const trimmed = (value ?? "").trim();
  if (!trimmed) {
    throw new Error("image_gen.base_url must be configured.");
  }
  let url: URL;
  try {
    url = new URL(trimmed);
  } catch {
    throw new Error(`image_gen.base_url must be a valid URL, got "${trimmed}".`);
  }
  if (!/^https?:$/.test(url.protocol)) {
    throw new Error("image_gen.base_url must use http or https.");
  }
  return trimmed.replace(/\/+$/, "");
}

function normalizeSubdir(value: string | undefined): string {
  const raw = (value ?? DEFAULT_OUTPUT_SUBDIR).trim();
  const portable = raw.replace(/\\/g, "/").replace(/^\.\/+/, "").replace(/\/+$/, "");
  if (!portable || portable === "." || portable === ".." || portable.startsWith("/") || portable.includes("../")) {
    throw new Error("image_gen.output_subdir must be a safe workspace-relative subdirectory.");
  }
  return portable;
}

function mimeToExtension(mimeType: string): string {
  const m = mimeType.split(";")[0]?.trim().toLowerCase() ?? "";
  switch (m) {
    case "image/jpeg":
    case "image/jpg":
      return "jpg";
    case "image/png":
      return "png";
    case "image/webp":
      return "webp";
    case "image/gif":
      return "gif";
    default:
      // Allow-list only — mirror danbooru's inferExtension hardening. The MIME
      // comes from the trusted Gemini response, but pinning the on-disk
      // extension to a vetted set keeps an unexpected subtype from dictating it.
      return "png";
  }
}

function imageMimeFromContentType(contentType: string | undefined): string | undefined {
  const raw = contentType?.split(";")[0]?.trim().toLowerCase();
  return raw?.startsWith("image/") ? raw : undefined;
}

function imageMimeFromExtension(ref: string): string | undefined {
  const ext = path.extname(ref).replace(/^\./, "").toLowerCase();
  switch (ext) {
    case "jpg":
    case "jpeg":
      return "image/jpeg";
    case "png":
      return "image/png";
    case "webp":
      return "image/webp";
    case "gif":
      return "image/gif";
    default:
      return undefined;
  }
}

function sanitizeFileBaseName(value: string | undefined): string | undefined {
  const raw = value?.trim();
  if (!raw) return undefined;
  const base = path.basename(raw, path.extname(raw));
  const cleaned = base.replace(/[^A-Za-z0-9._-]+/g, "-").replace(/^-+|-+$/g, "");
  return cleaned || undefined;
}

function toWorkspaceRelative(workspaceRoot: string, absolutePath: string): string {
  const relative = path.relative(workspaceRoot, absolutePath);
  return relative.startsWith("..") ? absolutePath : `./${relative.replace(/\\/g, "/")}`;
}

function errMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function textError(message: string) {
  return {
    content: [{ type: "text" as const, text: `error: ${message}` }],
    details: { error: message },
  };
}
